
const card = [
    {
        id: 1,
        foto: "/src/assets/img/imagem.jpg",
        nome: "JBM202 - Suite Top vista mar resort Jurere",
        info: "Jurerê Internacional . 8 hópedes . 2 quartos",
        valorDiaria: "R$700,00 / noite",
        cincoDiarias: "R$3500,00",
        limpeza: "R$200,00",
        caucao: "R$1850,00",
        total: "R$3700,00",
        aVista: "R$3350",
        bairro: "Jurere Internacional",
        localizacao: "Av. Buzio 1800, Jurerê Internacional, Florianópolis	- SC, ",
        cep: "89650-100",
        comodos: "2 quartos . 3 camas . 2 banheiros",
        status: "ativo",
        maxHospedes: "6",
        aceitaCrianca: "sim",
        aceitaBebes: "sim",
        forneceBercos: "nao",
        restricaoIdade: "nao",
        fumar: "nao",
        animais: "nao",
        eventos: "sim",
        estacionamento: "nao",
        elevador: "sim",
        porteiro: "sim",
        piscinaPrivada: "nao",
        camera: "sim",
        piscinaPublica: "sim",
        internet: "sim",
        wifi: "sim",
        arCondicionado: "nao",
        trava: "sim",




    },
    {
        id: 2,
        foto: "/src/assets/img/imagem2.jpg",
        nome: "CCP109 - Casa Charmosa com Piscina",
        info: "Campeche . 6 hóspedes . 3 quartos",
        valorDiaria: "R$550,00 / noite",
        cincoDiarias: "R$2750,00",
        limpeza: "R$150,00",
        caucao: "R$1000,00",
        total: "R$3900,00",
        aVista: "R$3500",
        bairro: "Campeche",
        localizacao: "Rua das Andorinhas, 1800, Campeche, Florianópolis - SC",
        cep: "88063-500",
        comodos: "3 quartos . 2 camas . 2 banheiros",
        status: "ativo",
        maxHospedes: "6",
        aceitaCrianca: "sim",
        aceitaBebes: "sim",
        forneceBercos: "sim",
        restricaoIdade: "nao",
        fumar: "nao",
        animais: "nao",
        eventos: "nao",
        estacionamento: "sim",
        elevador: "nao",
        porteiro: "nao",
        piscinaPrivada: "sim",
        camera: "nao",
        piscinaPublica: "nao",
        internet: "sim",
        wifi: "sim",
        arCondicionado: "sim",
        trava: "nao",
    },
    {
        id: 3,
        foto: "/src/assets/img/imagem3.jpg",
        nome: "VMC205 - Apartamento Vista Mar",
        info: "Canasvieiras . 4 hóspedes . 1 quarto",
        valorDiaria: "R$400,00 / noite",
        cincoDiarias: "R$2000,00",
        limpeza: "R$100,00",
        caucao: "R$800,00",
        total: "R$2900,00",
        aVista: "R$2600",
        bairro: "Canasvieiras",
        localizacao: "Rua dos Coqueiros, 220, Canasvieiras, Florianópolis - SC",
        cep: "88054-200",
        comodos: "1 quarto . 1 cama . 1 banheiro",
        status: "ativo",
        maxHospedes: "4",
        aceitaCrianca: "sim",
        aceitaBebes: "nao",
        forneceBercos: "nao",
        restricaoIdade: "nao",
        fumar: "nao",
        animais: "nao",
        eventos: "nao",
        estacionamento: "nao",
        elevador: "sim",
        porteiro: "sim",
        piscinaPrivada: "nao",
        camera: "sim",
        piscinaPublica: "sim",
        internet: "sim",
        wifi: "sim",
        arCondicionado: "nao",
        trava: "nao",
    },
    {
        id: 4,
        foto: "/src/assets/img/imagem4.jpg",
        nome: "NCJ305 - Sobrado Natureza e Conforto",
        info: "Lagoa da Conceição . 10 hóspedes . 4 quartos",
        valorDiaria: "R$800,00 / noite",
        cincoDiarias: "R$4000,00",
        limpeza: "R$180,00",
        caucao: "R$2000,00",
        total: "R$6180,00",
        aVista: "R$5500",
        bairro: "Lagoa da Conceição",
        localizacao: "Rua das Bromélias, 750, Lagoa da Conceição, Florianópolis - SC",
        cep: "88062-350",
        comodos: "4 quartos . 4 camas . 3 banheiros",
        status: "ativo",
        maxHospedes: "10",
        aceitaCrianca: "nao",
        aceitaBebes: "sim",
        forneceBercos: "sim",
        restricaoIdade: "nao",
        fumar: "nao",
        animais: "sim",
        eventos: "sim",
        estacionamento: "sim",
        elevador: "nao",
        porteiro: "nao",
        piscinaPrivada: "nao",
        camera: "sim",
        piscinaPublica: "sim",
        internet: "sim",
        wifi: "sim",
        arCondicionado: "sim",
        trava: "sim",
    },
    {
        id: 5,
        foto: "/src/assets/img/imagem5.jpg",
        nome: "PRB401 - Casa Estilo e Relaxamento",
        info: "Praia Brava . 12 hóspedes . 5 quartos",
        valorDiaria: "R$900,00 / noite",
        cincoDiarias: "R$4500,00",
        limpeza: "R$200,00",
        caucao: "R$2500,00",
        total: "R$7200,00",
        aVista: "R$6500",
        bairro: "Praia Brava",
        localizacao: "Av. das Conchas, 480, Praia Brava, Florianópolis - SC",
        cep: "88056-245",
        comodos: "5 quartos . 6 camas . 4 banheiros",
        status: "ativo",
        maxHospedes: "12",
        aceitaCrianca: "nao",
        aceitaBebes: "nao",
        forneceBercos: "nao",
        restricaoIdade: "nao",
        fumar: "sim",
        animais: "sim",
        eventos: "sim",
        estacionamento: "sim",
        elevador: "nao",
        porteiro: "nao",
        piscinaPrivada: "nao",
        camera: "nao",
        piscinaPublica: "nao",
        internet: "sim",
        wifi: "sim",
        arCondicionado: "sim",
        trava: "nao",
    },
    {
        id: 6,
        foto: "/src/assets/img/imagem6.jpg",
        nome: "CPU207 - Apartamento Praticidade Urbana",
        info: "Centro . 3 hóspedes . 1 quarto",
        valorDiaria: "R$300,00 / noite",
        cincoDiarias: "R$1500,00",
        limpeza: "R$80,00",
        caucao: "R$500,00",
        total: "R$2080,00",
        aVista: "R$1900",
        bairro: "Centro",
        localizacao: "Rua do Comércio, 50, Centro, Florianópolis - SC",
        cep: "88010-300",
        comodos: "1 quarto . 1 cama . 1 banheiro",
        status: "ativo",
        maxHospedes: "3",
        aceitaCrianca: "sim",
        aceitaBebes: "sim",
        forneceBercos: "nao",
        restricaoIdade: "sim",
        fumar: "nao",
        animais: "nao",
        eventos: "nao",
        estacionamento: "sim",
        elevador: "sim",
        porteiro: "nao",
        piscinaPrivada: "nao",
        camera: "sim",
        piscinaPublica: "sim",
        internet: "sim",
        wifi: "sim",
        arCondicionado: "nao",
        trava: "sim",
    },
];

export default card;